### ISSUE TITLE
关于css命名规则的一些疑惑

### ISSUE THREAD

**Issue by Rockergmail** [jiandanxinli/jiandanxinli.github.io#22]
前段时间拜读了贵组织写的[css命名规范总结](https://jiandanxinli.github.io/2016-08-11.html)，收益良多。然后最近我在写自己的css lib，遇到了一个问题，就是关于文中“BEM + 命名空间”，我分不清楚object和component的区别，或许说component大概知道是什么，但是object理解起来有点抽象，能不能再举其他例子？先谢谢了。

**Comment by zfben** [comment]
@Rockergmail 才注意到这里，object 可以视为更大、更抽象的 component，实际项目中，如果架构不是非常复杂，可以不必严格区分。

**Comment by Rockergmail** [comment]
好的谢谢
